import type { Metadata } from "next";
import localFont from 'next/font/local';
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/home.scss";
import "./styles/booking.scss";
import "./styles/calendar.scss";
import "./styles/cosmetic_category.scss";
import "./styles/cosmetic_service.scss";
import "./styles/guest_details.scss";
import "./styles/time_picker.scss";
import "./styles/review.scss";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false;

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const Poppins = localFont({
  src: [
    {
      path: './fonts/Poppins-Black.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: './fonts/Poppins-ExtraBold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Poppins-Bold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Poppins-SemiBold.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Poppins-Medium.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Poppins-Regular.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/Poppins-Light.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/Poppins-Thin.ttf',
      weight: '100',
      style: 'normal',
    },
  ],
  variable: '--font-Poppins',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
